user:
  memory-limit: 2
  message-length: 256
  userId-length:  2
server:
  http2:
    enabled: true
spring:
  redis:
    cluster:
      nodes: localhost:7000,localhost:7002,localhost:7001
      max-redirects: 5
storage: redis

redisson:
  cluster-servers-config:
    node-addresses: redis://127.0.0.1:7000,redis://127.0.0.1:7001,redis://127.0.0.1:7002
    scan-interval: 2000
    slave-connection-pool-size: 64
    master-connection-pool-size: 64

